### ISSUE TITLE
Transaction list wiped out

### ISSUE THREAD

**Issue by mr10008** [TrustWallet/trust-wallet-android#160]
Last month I did some testing on Ropsten network. The transaction list of all these transactions is now wiped out, but the wallet balance shows right amounts. 
New transactions and list is displayed OK.
Is that a bug?

**Comment by michaelScoff** [comment]
@mr10008 transactions node should be back pretty soon! we did maintenance for the https://github.com/TrustWallet/trust-ray

@kolya182 let's make sure this is fixed today.

**Comment by mr10008** [comment]
Updated to the latest version 1.4.35 but the history from the previous month is still not available. The balance is displayed.

**Comment by michaelScoff** [comment]
@mr10008 I’m gonna look at it tonight

**Comment by michaelScoff** [comment]
@mr10008 can you check this endpoint: https://ropsten.trustwalletapp.com

It is parsing from the last block to 0, once those parsed you should be able to see transactions for your wallet.
